### ISSUE TITLE
Camera Hight locked

### ISSUE THREAD

**Issue by BenjaminVockenberg** [ColormaticStudios/quality-godot-first-person-2#17]
Hallo there. I'm relatively new to Godot4 and I hope I can find help for my noob problems here.

The FPSTemplate is really greate and it helped me a lot learning how to get use of the Nodes in Godot.

But I'm facing a problem at the moment. For my LevelDesign, I need to move the Camera of the FPSInstance a bit, but when I save the scene, the camer jumps to its original position. 

I tried to find the place where the lock could have been located but I cannot find it.

Can you pls help me out with it?

Thanks a lot for help and for the great template.

Greetings froom Germany :)

**Comment by CZakarya** [comment]
Right, I got so caught up in other things that I never got around to this issue. I even added a comment in the code that was because of this. I think the solution is to change the RESET animations on all of the AnimationPlayer nodes (CrouchAnimation, HeadbobAnimation, JumpAnimation).

**Comment by big-Palooka** [comment]
For anyone who has this issue, modify the Head's position value in the CrouchAnimation's RESET animation
