### ISSUE TITLE
Camera jitter

### ISSUE THREAD

**Issue by Knockturnal** [ColormaticStudios/quality-godot-first-person-2#21]
First of all thank you for this project, it saves a lot of work for fast prototyping. I have identified an issue and have a simple fix for it:

Reproduction:
Move close to an object and move around it in circles while compensating with the mouse to look at the object. For instance, run circles around a tree while looking at said tree.

Result:
The camera is incredibly jittery. This happens at all times actually, it's just more noticeable in this scenario

Fix:
The fix is actually super simple, I will do a PR but here's the explanation:

First create a variable to store mouse input

```python
var mouseInput : Vector2 = Vector2(0,0)
```

Then replace the __unhandled_input_ function with this:

```python
func _unhandled_input(event):
	if event is InputEventMouseMotion and Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:
		mouseInput.x += event.relative.x
		mouseInput.y += event.relative.y
```

We're accumulating the input data to consume it when we want to, not immediately which would be outside the physics loop. We consume it in a function like this:

```python
func handle_rotation():
	HEAD.rotation_degrees.y -= mouseInput.x * mouse_sensitivity
	HEAD.rotation_degrees.x -= mouseInput.y * mouse_sensitivity
	mouseInput = Vector2(0,0)
```
	
Lastly, call this function somewhere within __physics_process_. This all assures that we don't rotate and move the camera out of step, which causes jitter. I am no Godot expert but I have a decade + of game dev experience and this is an extremely common issue which is why I immediately knew how to mitigate it

**Comment by CZakarya** [comment]
Yeah, this makes sense. All physical changes need to be made in `_physics_process`. I know that now, but I didn't know that at the time. I'll test this with a controller.
