### ISSUE TITLE
Camera is lagging when exported

### ISSUE THREAD

**Issue by Disa-Kizonda** [ColormaticStudios/quality-godot-first-person-2#27]
When i play in godot editor it works fine but when it's exported camera is teleporting

https://github.com/user-attachments/assets/c4106a5b-7eaf-4428-aafd-60a7025f26ab

**Comment by Disa-Kizonda** [comment]
i think it's godot problem and not this plugin

**Comment by CZakarya** [comment]
> Just came across this and while this is an issue with the web export specifically, it can be remedied from the plugin code. I'm not sure if there's any adverse effects in other areas with this solution, but it seemed to work for me.
> 
> In ready:
> 
> ```
> if OS.get_name() == "Web":
>     Input.set_use_accumulated_input(false)
> ```
> 
> In _unhandled_input, replace the accumulative mouse input logic:
> 
> ```
> mouseInput = event.relative
> ```
> 
> I'd suggest testing and addressing this, cause otherwise this awesome FPS controller is completely unusable in web games.

Added ✔️ 
6dfad6ea9953950ee67eec576d1f0343b0f6ffb3
