### ISSUE TITLE
Sliding

### ISSUE THREAD

**Issue by Bump-Dev** [ColormaticStudios/quality-godot-first-person-2#3]
can u add sliding

**Comment by ColormaticStudios** [comment]
Sorry for a very delayed response. Sliding would be a pretty complex thing to add, but if there is demand for it then I will get to work on implementing it. I haven't really played any games that have sliding, (and if I have I didn't use it) but I can just look up how it works.

**Comment by ColormaticStudios** [comment]
Sliding is turning out to be a very difficult thing to add because I don't know what the end result looks like. Hopefully someone can figure this out in the future.
