### ISSUE TITLE
Jump boost when jump movement enabled

### ISSUE THREAD

**Issue by cbejl** [ColormaticStudios/quality-godot-first-person-2#32]
Jump bust when you walk in a low obstacle and then jump. idk how it work. in_air_momentum is false, and it works better when motion_smoothing disabled.

https://github.com/user-attachments/assets/0b3010e3-a431-4b2c-87a1-03384699cb99

**Comment by CZakarya** [comment]
I think what's happening here is the physics system is reporting that the player is on the ground for a moment, allowing the player to jump.

This can be solved by adding a cooldown timer for jumping.

**Comment by CZakarya** [comment]
Austin's work should have fixed this.
