### ISSUE TITLE
SPRINT and CROUCH var's are not used

### ISSUE THREAD

**Issue by ITWinVis** [ColormaticStudios/quality-godot-first-person-2#4]
The SPRINT and CROUCH variables are declared and exportet, but are not used in the actual actual code.

For Example, line 128 in character.gd should is:
   if Input.is_action_pressed("sprint") and !Input.is_action_pressed("crouch"):
Even though it should be:
   if Input.is_action_pressed(SPRINT) and !Input.is_action_pressed(CROUCH):

**Comment by ColormaticStudios** [comment]
That's a good point, I'll fix this
