### ISSUE TITLE
Rotating the player messes up direction

### ISSUE THREAD

**Issue by niandrei** [ColormaticStudios/quality-godot-first-person-2#5]
If you rotate the whole player by 90 deg on the Y axis for example, the movement keys don't work correctly anymore.

**Comment by ColormaticStudios** [comment]
The controller isn't designed for the CharacterBody to be rotated. Can you give me more details on your project, and why the CharacterBody is being rotated?

**Comment by niandrei** [comment]
When the scene loads, I would like the player to face a certain way. When I set the rotation 90 deg on Y axis, when I move forward the player goes to the side.

**Comment by ColormaticStudios** [comment]
Ah. That's a good point. Would it fix the issue if I added an "initial facing direction" value?

**Comment by niandrei** [comment]
I think so, yes :)

**Comment by ColormaticStudios** [comment]
The commit is out

**Comment by codecat** [comment]
Can it not pull the initial facing direction from the moment it gets loaded into the scene?
