### ISSUE TITLE
Notify people mor nicely that their actions are missing.

### ISSUE THREAD

**Issue by albinaask** [ColormaticStudios/quality-godot-first-person-2#8]
Thanks for making this plugin. It really helps speeding my development along!

I would wish it to check whether all actions exist in the _init or _ready or whatever so I instead of a million errors in the error log I instead get 1 warning in the normal log and then just some reduced functionality. Aka, failing gracefully instead of clogging my view.

**Comment by ColormaticStudios** [comment]
Fixed

**Comment by albinaask** [comment]
Niiice. Thanks!
